$ANSIBLE_VAULT;1.1;AES256
38633665383736303065303739626534363066626565396636353263313164616537343762383264
3437383037393037643030303038336666653632363365630a373131396231303265363334653732
36616563313665626631386132303239326630653632313964353530653231306230333162313736
3135383463333138660a373864333734666461336366626663363537343731343434663839663934
38353437353432653663356539663465356438343231383963636361333865363039646366336531
34623665633239623039323937396632616666383563656263643535396533366362346336306631
65613938636261383831653739313563613338326365646436313830643634336363323435373133
38633032396133313730346565346161623631623436666230666231666435623234636638663563
38633435343564373035613764346239303236383430646561656537333362636238383337653630
37623866346638306135383037373063373762353865353231303033643762306661326339363464
38653563336435656631383931383634393438626634326330613231643965353263306165393738
66626462633566343433
