$ANSIBLE_VAULT;1.1;AES256
61663437653033353465336334663536623138356365343861653565376163646137626363326638
3031663036633766643631656331323738666631666633620a656230663561653438346630333962
64356565383037383837633066623134336361333432376434333537313038613363326666373531
6331353463643538380a396438633966643339643035343736383465623531613437363063353836
65613033303038363662636465383464613066306436396463616361646134326633386465666535
6663313662306630373364343562393264393564643531303561
