- hosts: peryton, local 
  become: true
  roles:
    - role : system_update
      tags : [system_update]
    - role : docker
      tags : [docker]
    - role : certificats
      tags : [certificats]
    - role : services
      tags : [services]
    - role : etc_hosts
      tags : [etc_hosts]
    - role : gogs_config
      tags : [gogs]
    - role : vpn_users
      tags : [vpn_users]
    - role : ufw
      tags : [ufw, fail2ban]
    - role : fail2ban
      tags : [fail2ban]
    - role : send_credentials
      tags : [send_credentials]