- hosts: peryton, local 
  become: true
  roles:
    - role : docker
      tags : [docker]
    - role : certificats
      tags : [services, certificats]
    - role : services
      tags : [services,stack]
    - role : etc_hosts
      tags : [etc_hosts]
    - role : gogs_config
      tags : [services,gogs]
    - role : vpn_users
      tags : [services,vpn_users]
    - role : ufw
      tags : [ufw, fail2ban]
    - role : fail2ban
      tags : [fail2ban]