---
- name: Install UFW
  apt:
    name: ufw
    state: present
    update_cache: yes

- name: Reset UFW rules
  command: ufw --force reset

- name: Disable UFW before configuration
  ufw:
    state: disabled

- name: Set default policy for incoming traffic (deny)
  ufw:
    direction: incoming
    policy: deny

- name: Set default policy for outgoing traffic (allow)
  ufw:
    direction: outgoing
    policy: allow

# Allow SSH from internal networks defined in the vault
- name: Allow SSH from internal networks
  ufw:
    rule: allow
    port: 22
    proto: tcp

- name: Allow Wireguard (51820) UDP from anywhere
  ufw:
    rule: allow
    port: 51820
    proto: udp

- name: Enable UFW
  ufw:
    state: enabled
    direction: in
