---
# defaults file for system_update

# Unattended upgrades configuration
unattended_upgrades_origins:
  - '${distro_id}:${distro_codename}-security'
  - '${distro_id}ESMApps:${distro_codename}-apps-security'
  - '${distro_id}ESM:${distro_codename}-infra-security'

unattended_upgrades_auto_fix_interrupted_dpkg: true
unattended_upgrades_minimal_steps: true
unattended_upgrades_install_on_shutdown: false
unattended_upgrades_mail: ""
unattended_upgrades_mail_report: "on-change"
unattended_upgrades_remove_unused_kernel_packages: true
unattended_upgrades_remove_unused_dependencies: true
unattended_upgrades_automatic_reboot: false
unattended_upgrades_automatic_reboot_time: "02:00"
unattended_upgrades_update_days: "{}"

# Auto-upgrades configuration
auto_upgrades_update_package_lists: "1"
auto_upgrades_unattended_upgrade: "1"
auto_upgrades_auto_clean_interval: "7"
auto_upgrades_download_upgradeable_packages: "1"
