---
directories:
  - path: /server
    owner: "{{user}}"
    group: "{{user}}"
    mode: '0755'

  - path: /server/caddy
    owner: "{{user}}"
    group: "{{user}}"
    mode: '0755'
  - path: /server/caddy/logs
    owner: "root"
    group: "root"
    mode: '0755'

  - path: /server/homepage
    owner: "{{user}}"
    group: "{{user}}"
    mode: '0755'
  - path: /server/homepage/config
    owner: "{{user}}"
    group: "{{user}}"
    mode: '0755'
  - path: /server/homepage/images
    owner: "{{user}}"
    group: "{{user}}"
    mode: '0755'

  - path: /server/wg-easy
    owner: "{{user}}"
    group: "{{user}}"
    mode: '0755'

  - path: /server/gogs
    owner: "{{user}}"
    group: "{{user}}"
    mode: '0755'
  - path: /server/gogs/gogs
    owner: "{{user}}"
    group: "{{user}}"
    mode: '0755'
  - path: /server/gogs/gogs/conf
    owner: "{{user}}"
    group: "{{user}}"
    mode: '0755'

  - path: /server/pihole
    owner: "{{user}}"
    group: "{{user}}"
    mode: '0755'
  - path: /server/pihole/etc-pihole
    owner: "{{user}}"
    group: "{{user}}"
    mode: '0755'

  - path: /server/ressources
    owner: "{{user}}"
    group: "{{user}}"
    mode: '0755'
  - path: /server/fqcm
    owner: "{{user}}"
    group: "{{user}}"
    mode: '0755'
  - path: /server/fqcm/output
    owner: "{{user}}"
    group: "{{user}}"
    mode: '0755'
  - path: /server/ressources/courses
    owner: "{{user}}"
    group: "{{user}}"
    mode: '0755'

  - path: /server/docsify
    owner: "{{user}}"
    group: "{{user}}"
    mode: '0755'
