---
# tasks file for services

- name: Create directories
  file:
    path: "{{ item.path }}"
    state: directory
    owner: "{{ item.owner }}"
    group: "{{ item.group }}"
    mode: "{{ item.mode }}"
    recurse: yes
  loop: "{{ directories }}"

- name: Copy compose
  template:
    src: compose.yml.j2
    dest: /server/compose.yml
    owner: "{{user}}"
    group: "{{user}}"
    mode: '0640'

- name: Stop compose
  shell: docker compose down
  args:
    chdir: /server
  ignore_errors: yes

- name: Copy caddyfile
  template:
    src: Caddyfile.j2
    dest: /server/caddy/Caddyfile
    owner: "{{user}}"
    group: "{{user}}"
    mode: '0644'

- name: homepage image
  ansible.builtin.copy:
    src: peryton.png
    dest: /server/homepage/images/peryton.png
    owner: "{{user}}"
    group: "{{user}}"
    mode: '0644'

- name: homepage settings
  ansible.builtin.copy:
    src: settings.yaml
    dest: /server/homepage/config/settings.yaml
    owner: "{{user}}"
    group: "{{user}}"
    mode: '0644'

- name: homepage bookmark
  ansible.builtin.copy:
    src: bookmarks.yaml
    dest: /server/homepage/config/bookmarks.yaml
    owner: "{{user}}"
    group: "{{user}}"
    mode: '0644'

- name: homepage services
  template:
    src: services.yaml.j2
    dest: /server/homepage/config/services.yaml
    owner: "{{user}}"
    group: "{{user}}"
    mode: '0644'


- name: Docsify index.html
  copy:
    src: index.html
    dest: /server/docsify/index.html
    owner: "{{user}}"
    group: "{{user}}"
    mode: '0644'

- name: Docsify README.md
  copy:
    src: README.md
    dest: /server/docsify/README.md
    owner: "{{user}}"
    group: "{{user}}"
    mode: '0644'

# gogs configuration is done in gogs role

- name: pihole configuration file
  copy:
    src: pihole.toml
    dest: /server/pihole/etc-pihole/pihole.toml
    owner: "{{user}}"
    group: "{{user}}"
    mode: '0644'



- name: Update images
  shell: docker compose pull
  args:
    chdir: /server

- name: Start compose
  shell: docker compose up -d
  args:
    chdir: /server
