---
# Default variables for Fail2Ban and UFW configuration

fail2ban_bantime: 3600        # Ban time in seconds
fail2ban_findtime: 600        # Find time in seconds
fail2ban_maxretry: 1          # Max retry attempts
fail2ban_logpath: /server/caddy/logs/access.log  # Path to Caddy's access log
fail2ban_filter_name: caddy-json  # Name of the custom filter
fail2ban_jail_name: caddy-json    # Name of the jail